import type { TemplateRoute } from "../../types";

export const DISPATCH_TEMPLATE_ROUTES: readonly TemplateRoute[] = [
  ["ModelList", "OpenAi", "ModelList", "OpenAi"],
  ["ModelList", "Claude", "ModelList", "OpenAi"],
  ["ModelList", "Gemini", "ModelList", "OpenAi"],
  ["ModelGet", "OpenAi", "ModelGet", "OpenAi"],
  ["ModelGet", "Claude", "ModelGet", "OpenAi"],
  ["ModelGet", "Gemini", "ModelGet", "OpenAi"],
  ["CountToken", "OpenAi", "CountToken", "OpenAi", "local"],
  ["CountToken", "Claude", "CountToken", "OpenAi", "local"],
  ["CountToken", "Gemini", "CountToken", "OpenAi", "local"],
  ["GenerateContent", "OpenAi", "GenerateContent", "OpenAiChatCompletion"],
  ["GenerateContent", "OpenAiChatCompletion", "GenerateContent", "OpenAiChatCompletion"],
  ["GenerateContent", "Claude", "GenerateContent", "OpenAiChatCompletion"],
  ["GenerateContent", "Gemini", "GenerateContent", "OpenAiChatCompletion"],
  ["OpenAiResponseWebSocket", "OpenAi", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["GeminiLive", "Gemini", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["StreamGenerateContent", "OpenAi", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["StreamGenerateContent", "OpenAiChatCompletion", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["StreamGenerateContent", "Claude", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["StreamGenerateContent", "Gemini", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["StreamGenerateContent", "GeminiNDJson", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["CreateImage", "OpenAi", "CreateImage", "OpenAi"],
  ["StreamCreateImage", "OpenAi", "StreamCreateImage", "OpenAi"],
  ["CreateImageEdit", "OpenAi", "CreateImageEdit", "OpenAi", "unsupported"],
  ["StreamCreateImageEdit", "OpenAi", "StreamCreateImageEdit", "OpenAi", "unsupported"],
  ["CreateVideo", "OpenAi", "CreateVideo", "OpenAi"],
  ["VideoGet", "OpenAi", "VideoGet", "OpenAi"],
  ["VideoContentGet", "OpenAi", "VideoContentGet", "OpenAi"],
  ["Compact", "OpenAi", "GenerateContent", "OpenAiChatCompletion"],
  ["Embedding", "OpenAi", "Embedding", "OpenAi", "unsupported"],
  ["Embedding", "Gemini", "Embedding", "OpenAi", "unsupported"]
];
