//! Admin config CRUD handlers for the GLOBAL config entities (native-only).
//!
//! Each entity gets four handlers — `list` / `get` / `upsert` / `delete` —
//! generated by the [`crud_entity!`] macro from a small spec, so the 28
//! handlers are not hand-copied. Users are special-cased in [`users`] (password
//! hashing + hash redaction). All routes mount behind `require_admin`.

mod authz;
mod credentials;
mod entities;
mod nested;
mod user_keys;
mod users;

use axum::Router;
use axum::routing::get;

use crate::app::AppState;

/// Map a persistence error to a 500 (the cause is logged, not leaked).
pub(crate) fn internal<E: std::fmt::Display>(e: E) -> crate::api::error::ApiError {
    crate::api::error::ApiError::Internal(e.to_string())
}

/// All global-entity CRUD routes, to be merged into the protected subrouter.
pub fn routes() -> Router<AppState> {
    Router::new()
        .route(
            "/admin/orgs",
            get(entities::orgs::list).post(entities::orgs::upsert),
        )
        .route(
            "/admin/orgs/{id}",
            get(entities::orgs::get).delete(entities::orgs::delete),
        )
        .route(
            "/admin/providers",
            get(entities::providers::list).post(entities::providers::upsert),
        )
        .route(
            "/admin/providers/{id}",
            get(entities::providers::get).delete(entities::providers::delete),
        )
        .route(
            "/admin/routes",
            get(entities::routes::list).post(entities::routes::upsert),
        )
        .route(
            "/admin/routes/{id}",
            get(entities::routes::get).delete(entities::routes::delete),
        )
        .route(
            "/admin/aliases",
            get(entities::aliases::list).post(entities::aliases::upsert),
        )
        .route(
            "/admin/aliases/{id}",
            get(entities::aliases::get).delete(entities::aliases::delete),
        )
        .route(
            "/admin/rule-sets",
            get(entities::rule_sets::list).post(entities::rule_sets::upsert),
        )
        .route(
            "/admin/rule-sets/{id}",
            get(entities::rule_sets::get).delete(entities::rule_sets::delete),
        )
        .route(
            "/admin/instance-settings",
            get(entities::instance_settings::list).post(entities::instance_settings::upsert),
        )
        .route("/admin/users", get(users::list).post(users::upsert))
        .route("/admin/users/{id}", get(users::get).delete(users::delete))
        // M10b T2 — credentials (sealed secret, redacted on read).
        .route(
            "/admin/providers/{provider_id}/credentials",
            get(credentials::list).post(credentials::upsert),
        )
        .route(
            "/admin/providers/{provider_id}/credentials/{id}",
            get(credentials::get),
        )
        .route(
            "/admin/credentials/{id}",
            axum::routing::delete(credentials::delete),
        )
        // M10b T2 — user keys (digest + sealed ciphertext, redacted on read).
        .route(
            "/admin/users/{user_id}/keys",
            get(user_keys::list).post(user_keys::upsert),
        )
        .route(
            "/admin/user-keys/{id}",
            axum::routing::delete(user_keys::delete),
        )
        // M10b T2 — parent-nested config entities (no secrets).
        .route(
            "/admin/orgs/{org_id}/teams",
            get(nested::teams::list).post(nested::teams::upsert),
        )
        .route(
            "/admin/teams/{id}",
            axum::routing::delete(nested::teams::delete),
        )
        .route(
            "/admin/providers/{provider_id}/models",
            get(nested::provider_models::list).post(nested::provider_models::upsert),
        )
        .route(
            "/admin/provider-models/{id}",
            axum::routing::delete(nested::provider_models::delete),
        )
        .route(
            "/admin/routes/{route_id}/members",
            get(nested::route_members::list).post(nested::route_members::upsert),
        )
        .route(
            "/admin/route-members/{id}",
            axum::routing::delete(nested::route_members::delete),
        )
        .route(
            "/admin/rule-sets/{rule_set_id}/rules",
            get(nested::rules::list).post(nested::rules::upsert),
        )
        .route(
            "/admin/rules/{id}",
            axum::routing::delete(nested::rules::delete),
        )
        .route(
            "/admin/providers/{provider_id}/routing-rules",
            get(nested::routing_rules::list).post(nested::routing_rules::upsert),
        )
        .route(
            "/admin/routing-rules/{id}",
            axum::routing::delete(nested::routing_rules::delete),
        )
        .route(
            "/admin/providers/{provider_id}/rule-sets",
            get(nested::provider_rule_sets::list).post(nested::provider_rule_sets::upsert),
        )
        .route(
            "/admin/provider-rule-sets/{id}",
            axum::routing::delete(nested::provider_rule_sets::delete),
        )
        // M10b T3 — authz scoped entities (no secrets), keyed by ?scope&scope_id.
        .route(
            "/admin/route-permissions",
            get(authz::list_route_permissions).post(authz::upsert_route_permission),
        )
        .route(
            "/admin/route-permissions/{id}",
            axum::routing::delete(authz::delete_route_permission),
        )
        .route(
            "/admin/rate-limits",
            get(authz::list_rate_limits).post(authz::upsert_rate_limit),
        )
        .route(
            "/admin/rate-limits/{id}",
            axum::routing::delete(authz::delete_rate_limit),
        )
        .route(
            "/admin/quotas",
            get(authz::get_quota).post(authz::upsert_quota),
        )
        .route(
            "/admin/quotas/{id}",
            axum::routing::delete(authz::delete_quota),
        )
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use axum::body::Body;
    use axum::http::{Request, StatusCode, header};
    use http_body_util::BodyExt as _;
    use tower::ServiceExt as _;

    use crate::app::AppState;
    use crate::app::snapshot::ControlPlaneSnapshot;
    use crate::config::{CacheConfig, PersistenceConfig, RuntimeConfig, UpstreamConfig};
    use crate::http::client::{ClientError, RespStream, UpstreamClient};
    use crate::store::persistence::FilePersistence;
    use crate::store::persistence::records::{OrgInput, UserInput};

    struct NoUpstream;
    #[async_trait::async_trait]
    impl UpstreamClient for NoUpstream {
        async fn send(
            &self,
            _req: http::Request<bytes::Bytes>,
        ) -> Result<http::Response<bytes::Bytes>, ClientError> {
            unreachable!("crud tests do not call upstream")
        }
        async fn send_streaming(
            &self,
            _req: http::Request<bytes::Bytes>,
        ) -> Result<(StatusCode, http::HeaderMap, RespStream), ClientError> {
            unreachable!("crud tests do not call upstream")
        }
    }

    /// AppState backed by a tempdir file store seeded with one admin
    /// (`admin` / `secret`). Returns the state, its tempdir, and the admin id.
    async fn seeded_state() -> (AppState, tempfile::TempDir, i64) {
        seeded_state_with_cipher(Arc::new(crate::crypto::NoopCipher)).await
    }

    /// As [`seeded_state`] but with a caller-supplied cipher (so secret-bearing
    /// tests can use a real envelope cipher).
    async fn seeded_state_with_cipher(
        cipher: Arc<dyn crate::crypto::SecretCipher>,
    ) -> (AppState, tempfile::TempDir, i64) {
        let dir = tempfile::tempdir().expect("tempdir");
        let persistence: Arc<dyn crate::store::persistence::PersistenceBackend> = Arc::new(
            FilePersistence::open(dir.path().to_path_buf())
                .await
                .expect("open"),
        );
        let org = persistence
            .upsert_org(OrgInput {
                id: None,
                name: "default".into(),
                enabled: true,
                description: None,
            })
            .await
            .unwrap();
        let admin = persistence
            .upsert_user(UserInput {
                id: None,
                name: "admin".into(),
                org_id: org.id,
                team_id: None,
                password: Some(crate::crypto::password::hash("secret").unwrap()),
                enabled: true,
                is_admin: true,
            })
            .await
            .unwrap();

        let snapshot = ControlPlaneSnapshot::build(persistence.as_ref(), 1)
            .await
            .expect("snapshot");
        let config = Arc::new(RuntimeConfig {
            host: "127.0.0.1".into(),
            port: 0,
            cache: CacheConfig::Memory,
            persistence: PersistenceConfig::File {
                data_dir: dir.path().to_path_buf(),
            },
            upstream: UpstreamConfig::from_proxy_url(None),
            instance_id: 0,
            max_attempts: crate::config::DEFAULT_MAX_ATTEMPTS,
        });
        let cache: Arc<dyn crate::store::cache::CacheBackend> =
            Arc::new(crate::store::cache::MemoryCache::new());
        let snapshot = Arc::new(arc_swap::ArcSwap::from_pointee(snapshot));
        let channels = Arc::new(crate::channel::registry::ChannelRegistry::with_builtin());
        let state = AppState::new(
            config,
            cache,
            persistence,
            Arc::new(NoUpstream),
            snapshot,
            channels,
            cipher,
        );
        (state, dir, admin.id)
    }

    fn insecure_cookies() {
        // SAFETY: single-threaded test setup before any server call.
        unsafe { std::env::set_var("GPROXY_INSECURE_COOKIES", "1") };
    }

    /// Mint a session for `admin_id` and return the `gproxy_session=…` cookie.
    async fn admin_cookie(state: &AppState, admin_id: i64) -> String {
        let token = crate::admin::session::create(state.cache.as_ref(), admin_id).await;
        format!("{}={token}", crate::admin::session::cookie_name())
    }

    #[tokio::test]
    async fn orgs_crud_roundtrip() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let app = crate::http::server::router(state);

        // Unauthed → 401.
        let resp = app
            .clone()
            .oneshot(Request::get("/admin/orgs").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::UNAUTHORIZED);

        // POST create → 200, capture id.
        let resp = app
            .clone()
            .oneshot(
                Request::post("/admin/orgs")
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        r#"{"name":"acme","enabled":true,"description":null}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let created: serde_json::Value = serde_json::from_slice(&body).unwrap();
        let id = created["id"].as_i64().unwrap();

        // GET list contains it.
        let resp = app
            .clone()
            .oneshot(
                Request::get("/admin/orgs")
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(list.as_array().unwrap().iter().any(|o| o["id"] == id));

        // GET by id.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!("/admin/orgs/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);

        // DELETE → 204, then GET → 404.
        let resp = app
            .clone()
            .oneshot(
                Request::delete(format!("/admin/orgs/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::NO_CONTENT);
        let resp = app
            .oneshot(
                Request::get(format!("/admin/orgs/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn mutation_invalidates_snapshot() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let before = state.cp().version;
        let app = crate::http::server::router(state.clone());

        let resp = app
            .oneshot(
                Request::post("/admin/orgs")
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        r#"{"name":"beta","enabled":true,"description":null}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        assert!(state.cp().version > before, "snapshot version should bump");
    }

    #[tokio::test]
    async fn user_password_hashed_and_redacted() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let org_id = state.persistence.list_orgs().await.unwrap()[0].id;
        let app = crate::http::server::router(state);

        // POST create a user with a plaintext password.
        let payload = format!(
            r#"{{"name":"bob","org_id":{org_id},"password":"pw","enabled":true,"is_admin":true}}"#
        );
        let resp = app
            .clone()
            .oneshot(
                Request::post("/admin/users")
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(payload))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let created: serde_json::Value = serde_json::from_slice(&body).unwrap();
        let id = created["id"].as_i64().unwrap();
        assert!(created.get("password").is_none(), "no hash on create resp");

        // GET → redacted view: no hash, has_password:true.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!("/admin/users/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let view: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(view.get("password").is_none(), "GET must not leak the hash");
        assert_eq!(view["has_password"], true);

        // Login as bob with "pw" proves the stored hash is valid.
        let resp = app
            .oneshot(
                Request::post("/admin/login")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"username":"bob","password":"pw"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
    }

    /// Seed a provider and return its id (file store, NoopCipher path uses the
    /// state's persistence directly).
    async fn seed_provider(state: &AppState) -> i64 {
        use crate::store::persistence::records::ProviderInput;
        state
            .persistence
            .upsert_provider(ProviderInput {
                id: None,
                name: "p1".into(),
                channel: "openai".into(),
                label: None,
                settings_json: serde_json::json!({}),
                credential_strategy: "weighted".into(),
                proxy_url: None,
                tls_fingerprint: None,
                enabled: true,
            })
            .await
            .unwrap()
            .id
    }

    /// Credentials seal the plaintext secret on write and redact it on read.
    #[tokio::test]
    async fn credential_sealed_and_redacted() {
        use base64::Engine as _;
        insecure_cookies();
        let cipher = crate::crypto::cipher_from_master_key(Some(
            &base64::engine::general_purpose::STANDARD.encode([9u8; 32]),
        ))
        .unwrap();
        let (state, _dir, admin_id) = seeded_state_with_cipher(cipher).await;
        let cookie = admin_cookie(&state, admin_id).await;
        let provider_id = seed_provider(&state).await;
        let persistence = state.persistence.clone();
        let app = crate::http::server::router(state);

        // POST a credential with a plaintext secret.
        let resp = app
            .clone()
            .oneshot(
                Request::post(format!("/admin/providers/{provider_id}/credentials"))
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"secret_json":{"api_key":"sk-x"}}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let view: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(view.get("secret_json").is_none(), "must not leak secret");
        assert_eq!(view["has_secret"], true);
        let cred_id = view["id"].as_i64().unwrap();

        // GET list is redacted too.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!("/admin/providers/{provider_id}/credentials"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(list[0].get("secret_json").is_none(), "list must redact");

        // The persisted secret is a real envelope.
        let stored = persistence.get_credential(cred_id).await.unwrap().unwrap();
        assert!(crate::crypto::envelope::is_envelope(&stored.secret_json));

        // Update WITHOUT secret_json (change weight) → stored secret unchanged.
        let resp = app
            .oneshot(
                Request::post(format!("/admin/providers/{provider_id}/credentials"))
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(format!(r#"{{"id":{cred_id},"weight":50}}"#)))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let stored = persistence.get_credential(cred_id).await.unwrap().unwrap();
        assert_eq!(stored.weight, 50);
        let opened = persistence
            .get_credential(cred_id)
            .await
            .unwrap()
            .unwrap()
            .secret_json;
        // Re-open through the same cipher proves it still holds "sk-x".
        let key = base64::engine::general_purpose::STANDARD.encode([9u8; 32]);
        let reopen = crate::crypto::cipher_from_master_key(Some(&key)).unwrap();
        assert_eq!(reopen.open(&opened).unwrap()["api_key"], "sk-x");
    }

    /// User keys store a digest of the bare key and never echo it back.
    #[tokio::test]
    async fn user_key_digest_redacted() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let user_id = state.persistence.list_users().await.unwrap()[0].id;
        let persistence = state.persistence.clone();
        let app = crate::http::server::router(state);

        let resp = app
            .oneshot(
                Request::post(format!("/admin/users/{user_id}/keys"))
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"api_key":"sk-test"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let view: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(view.get("api_key").is_none(), "no bare key in response");
        let prefix = view["key_prefix"].as_str().unwrap();
        assert_eq!(prefix.len(), 8);
        let id = view["id"].as_i64().unwrap();

        let stored = persistence.get_user_key(id).await.unwrap().unwrap();
        assert_eq!(
            stored.api_key_digest,
            crate::pipeline::auth::key_digest("sk-test")
        );
    }

    /// Nested route-members CRUD: create → list → delete.
    #[tokio::test]
    async fn nested_route_members_crud() {
        use crate::store::persistence::records::RouteInput;
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let provider_id = seed_provider(&state).await;
        let route_id = state
            .persistence
            .upsert_route(RouteInput {
                id: None,
                name: "r1".into(),
                strategy: "weighted".into(),
                enabled: true,
                description: None,
            })
            .await
            .unwrap()
            .id;
        let app = crate::http::server::router(state);

        // POST a member.
        let payload = format!(
            r#"{{"route_id":{route_id},"provider_id":{provider_id},"upstream_model_id":"gpt-4o","weight":1,"tier":0,"enabled":true}}"#
        );
        let resp = app
            .clone()
            .oneshot(
                Request::post(format!("/admin/routes/{route_id}/members"))
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(payload))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let member: serde_json::Value = serde_json::from_slice(&body).unwrap();
        let member_id = member["id"].as_i64().unwrap();

        // List shows it.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!("/admin/routes/{route_id}/members"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(
            list.as_array()
                .unwrap()
                .iter()
                .any(|m| m["id"] == member_id)
        );

        // Delete → 204, list empty.
        let resp = app
            .clone()
            .oneshot(
                Request::delete(format!("/admin/route-members/{member_id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::NO_CONTENT);
        let resp = app
            .oneshot(
                Request::get(format!("/admin/routes/{route_id}/members"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(list.as_array().unwrap().is_empty());
    }

    /// Authz scoped CRUD: create a user-scoped route permission → list by that
    /// scope shows it → delete → list empty.
    #[tokio::test]
    async fn authz_route_permissions_crud() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let user_id = state.persistence.list_users().await.unwrap()[0].id;
        let app = crate::http::server::router(state);

        // POST create a user-scoped permission.
        let payload = format!(r#"{{"scope":"user","scope_id":{user_id},"route_pattern":"gpt-*"}}"#);
        let resp = app
            .clone()
            .oneshot(
                Request::post("/admin/route-permissions")
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(payload))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let created: serde_json::Value = serde_json::from_slice(&body).unwrap();
        let id = created["id"].as_i64().unwrap();

        // GET list by that scope shows it.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!(
                    "/admin/route-permissions?scope=user&scope_id={user_id}"
                ))
                .header(header::COOKIE, &cookie)
                .body(Body::empty())
                .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(list.as_array().unwrap().iter().any(|p| p["id"] == id));

        // DELETE → 204, then list empty.
        let resp = app
            .clone()
            .oneshot(
                Request::delete(format!("/admin/route-permissions/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::NO_CONTENT);
        let resp = app
            .oneshot(
                Request::get(format!(
                    "/admin/route-permissions?scope=user&scope_id={user_id}"
                ))
                .header(header::COOKIE, &cookie)
                .body(Body::empty())
                .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(list.as_array().unwrap().is_empty());
    }

    /// M10d read API: seed usage rows via persistence, then read them back
    /// through `/admin/usage` and `/admin/usage-rollups`; unauthed → 401.
    #[tokio::test]
    async fn usage_read_endpoints() {
        use crate::store::persistence::records::UsageInput;
        use rust_decimal::Decimal;
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let persistence = state.persistence.clone();
        for i in 0..2 {
            persistence
                .append_usage(UsageInput {
                    request_id: format!("req-{i}"),
                    at: 100,
                    route_name: Some("r".into()),
                    provider_id: None,
                    credential_id: None,
                    org_id: None,
                    team_id: None,
                    user_id: None,
                    user_key_id: None,
                    operation: "chat".into(),
                    kind: "openai".into(),
                    model: Some("gpt-4o".into()),
                    input_tokens: 10,
                    output_tokens: 20,
                    cache_read_tokens: 0,
                    cache_creation_5m_tokens: 0,
                    cache_creation_1h_tokens: 0,
                    cost: Decimal::ZERO,
                    latency_ms: 0,
                    usage_source: "counted".into(),
                    ended: "complete".into(),
                })
                .await
                .unwrap();
        }
        let app = crate::http::server::router(state);

        // Unauthed → 401.
        let resp = app
            .clone()
            .oneshot(Request::get("/admin/usage").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::UNAUTHORIZED);

        // GET /admin/usage → 200 + both seeded rows.
        let resp = app
            .clone()
            .oneshot(
                Request::get("/admin/usage?limit=10")
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(list.as_array().unwrap().len(), 2);
        assert!(list[0].get("secret_json").is_none());

        // GET /admin/usage-rollups (valid granularity) → 200.
        let resp = app
            .clone()
            .oneshot(
                Request::get("/admin/usage-rollups?granularity=day&from=0&to=9999999999")
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);

        // Bad granularity → 400.
        let resp = app
            .oneshot(
                Request::get("/admin/usage-rollups?granularity=decade&from=0&to=1")
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::BAD_REQUEST);
    }

    /// M10d read API: seed a credential status + an upstream request log via
    /// persistence, then read them back through the credential-health and log
    /// endpoints.
    #[tokio::test]
    async fn credential_status_and_logs() {
        use crate::store::persistence::records::{
            CredentialInput, CredentialStatusInput, UpstreamRequestInput,
        };
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let provider_id = seed_provider(&state).await;
        let persistence = state.persistence.clone();
        let cred = persistence
            .upsert_credential(CredentialInput {
                id: None,
                provider_id,
                name: None,
                kind: "api_key".into(),
                secret_json: serde_json::json!({}),
                weight: 1,
                rpm_limit: None,
                tpm_limit: None,
                proxy_url: None,
                tls_fingerprint: None,
                enabled: true,
            })
            .await
            .unwrap();
        persistence
            .upsert_credential_status(CredentialStatusInput {
                id: None,
                credential_id: cred.id,
                channel: "openai".into(),
                health_kind: "cooldown".into(),
                health_json: Some(serde_json::json!({"until": 200})),
                checked_at: Some(100),
                last_error: Some("429".into()),
            })
            .await
            .unwrap();
        persistence
            .append_upstream_request(UpstreamRequestInput {
                request_id: "req-up".into(),
                at: 100,
                provider_id: Some(provider_id),
                credential_id: Some(cred.id),
                url: "https://api.example/v1".into(),
                method: "POST".into(),
                status: 200,
                latency_ms: 42,
                headers_json: None,
                body: None,
            })
            .await
            .unwrap();
        let app = crate::http::server::router(state);

        // GET /admin/credentials/{id}/status → 200 + the status row.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!("/admin/credentials/{}/status", cred.id))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(list.as_array().unwrap().len(), 1);
        assert_eq!(list[0]["health_kind"], "cooldown");

        // GET /admin/logs/{rid}/upstream → 200 + the log row.
        let resp = app
            .oneshot(
                Request::get("/admin/logs/req-up/upstream")
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert_eq!(list.as_array().unwrap().len(), 1);
        assert_eq!(list[0]["request_id"], "req-up");
    }
}
