//! Admin config CRUD handlers for the GLOBAL config entities (native-only).
//!
//! Each entity gets four handlers — `list` / `get` / `upsert` / `delete` —
//! generated by the [`crud_entity!`] macro from a small spec, so the 28
//! handlers are not hand-copied. Users are special-cased in [`users`] (password
//! hashing + hash redaction). All routes mount behind `require_admin`.

mod entities;
mod users;

use axum::Router;
use axum::routing::get;

use crate::app::AppState;

/// Map a persistence error to a 500 (the cause is logged, not leaked).
fn internal<E: std::fmt::Display>(e: E) -> crate::api::error::ApiError {
    crate::api::error::ApiError::Internal(e.to_string())
}

/// All global-entity CRUD routes, to be merged into the protected subrouter.
pub fn routes() -> Router<AppState> {
    Router::new()
        .route(
            "/admin/orgs",
            get(entities::orgs::list).post(entities::orgs::upsert),
        )
        .route(
            "/admin/orgs/{id}",
            get(entities::orgs::get).delete(entities::orgs::delete),
        )
        .route(
            "/admin/providers",
            get(entities::providers::list).post(entities::providers::upsert),
        )
        .route(
            "/admin/providers/{id}",
            get(entities::providers::get).delete(entities::providers::delete),
        )
        .route(
            "/admin/routes",
            get(entities::routes::list).post(entities::routes::upsert),
        )
        .route(
            "/admin/routes/{id}",
            get(entities::routes::get).delete(entities::routes::delete),
        )
        .route(
            "/admin/aliases",
            get(entities::aliases::list).post(entities::aliases::upsert),
        )
        .route(
            "/admin/aliases/{id}",
            get(entities::aliases::get).delete(entities::aliases::delete),
        )
        .route(
            "/admin/rule-sets",
            get(entities::rule_sets::list).post(entities::rule_sets::upsert),
        )
        .route(
            "/admin/rule-sets/{id}",
            get(entities::rule_sets::get).delete(entities::rule_sets::delete),
        )
        .route(
            "/admin/instance-settings",
            get(entities::instance_settings::list).post(entities::instance_settings::upsert),
        )
        .route("/admin/users", get(users::list).post(users::upsert))
        .route("/admin/users/{id}", get(users::get).delete(users::delete))
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use axum::body::Body;
    use axum::http::{Request, StatusCode, header};
    use http_body_util::BodyExt as _;
    use tower::ServiceExt as _;

    use crate::app::AppState;
    use crate::app::snapshot::ControlPlaneSnapshot;
    use crate::config::{CacheConfig, PersistenceConfig, RuntimeConfig, UpstreamConfig};
    use crate::http::client::{ClientError, RespStream, UpstreamClient};
    use crate::store::persistence::FilePersistence;
    use crate::store::persistence::records::{OrgInput, UserInput};

    struct NoUpstream;
    #[async_trait::async_trait]
    impl UpstreamClient for NoUpstream {
        async fn send(
            &self,
            _req: http::Request<bytes::Bytes>,
        ) -> Result<http::Response<bytes::Bytes>, ClientError> {
            unreachable!("crud tests do not call upstream")
        }
        async fn send_streaming(
            &self,
            _req: http::Request<bytes::Bytes>,
        ) -> Result<(StatusCode, http::HeaderMap, RespStream), ClientError> {
            unreachable!("crud tests do not call upstream")
        }
    }

    /// AppState backed by a tempdir file store seeded with one admin
    /// (`admin` / `secret`). Returns the state, its tempdir, and the admin id.
    async fn seeded_state() -> (AppState, tempfile::TempDir, i64) {
        let dir = tempfile::tempdir().expect("tempdir");
        let persistence: Arc<dyn crate::store::persistence::PersistenceBackend> = Arc::new(
            FilePersistence::open(dir.path().to_path_buf())
                .await
                .expect("open"),
        );
        let org = persistence
            .upsert_org(OrgInput {
                id: None,
                name: "default".into(),
                enabled: true,
                description: None,
            })
            .await
            .unwrap();
        let admin = persistence
            .upsert_user(UserInput {
                id: None,
                name: "admin".into(),
                org_id: org.id,
                team_id: None,
                password: Some(crate::crypto::password::hash("secret").unwrap()),
                enabled: true,
                is_admin: true,
            })
            .await
            .unwrap();

        let snapshot = ControlPlaneSnapshot::build(persistence.as_ref(), 1)
            .await
            .expect("snapshot");
        let config = Arc::new(RuntimeConfig {
            host: "127.0.0.1".into(),
            port: 0,
            cache: CacheConfig::Memory,
            persistence: PersistenceConfig::File {
                data_dir: dir.path().to_path_buf(),
            },
            upstream: UpstreamConfig::from_proxy_url(None),
            instance_id: 0,
            max_attempts: crate::config::DEFAULT_MAX_ATTEMPTS,
        });
        let cache: Arc<dyn crate::store::cache::CacheBackend> =
            Arc::new(crate::store::cache::MemoryCache::new());
        let snapshot = Arc::new(arc_swap::ArcSwap::from_pointee(snapshot));
        let channels = Arc::new(crate::channel::registry::ChannelRegistry::with_builtin());
        let state = AppState::new(
            config,
            cache,
            persistence,
            Arc::new(NoUpstream),
            snapshot,
            channels,
            Arc::new(crate::crypto::NoopCipher),
        );
        (state, dir, admin.id)
    }

    fn insecure_cookies() {
        // SAFETY: single-threaded test setup before any server call.
        unsafe { std::env::set_var("GPROXY_INSECURE_COOKIES", "1") };
    }

    /// Mint a session for `admin_id` and return the `gproxy_session=…` cookie.
    async fn admin_cookie(state: &AppState, admin_id: i64) -> String {
        let token = crate::admin::session::create(state.cache.as_ref(), admin_id).await;
        format!("{}={token}", crate::admin::session::cookie_name())
    }

    #[tokio::test]
    async fn orgs_crud_roundtrip() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let app = crate::http::server::router(state);

        // Unauthed → 401.
        let resp = app
            .clone()
            .oneshot(Request::get("/admin/orgs").body(Body::empty()).unwrap())
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::UNAUTHORIZED);

        // POST create → 200, capture id.
        let resp = app
            .clone()
            .oneshot(
                Request::post("/admin/orgs")
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        r#"{"name":"acme","enabled":true,"description":null}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let created: serde_json::Value = serde_json::from_slice(&body).unwrap();
        let id = created["id"].as_i64().unwrap();

        // GET list contains it.
        let resp = app
            .clone()
            .oneshot(
                Request::get("/admin/orgs")
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let list: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(list.as_array().unwrap().iter().any(|o| o["id"] == id));

        // GET by id.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!("/admin/orgs/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);

        // DELETE → 204, then GET → 404.
        let resp = app
            .clone()
            .oneshot(
                Request::delete(format!("/admin/orgs/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::NO_CONTENT);
        let resp = app
            .oneshot(
                Request::get(format!("/admin/orgs/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::NOT_FOUND);
    }

    #[tokio::test]
    async fn mutation_invalidates_snapshot() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let before = state.cp().version;
        let app = crate::http::server::router(state.clone());

        let resp = app
            .oneshot(
                Request::post("/admin/orgs")
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(
                        r#"{"name":"beta","enabled":true,"description":null}"#,
                    ))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        assert!(state.cp().version > before, "snapshot version should bump");
    }

    #[tokio::test]
    async fn user_password_hashed_and_redacted() {
        insecure_cookies();
        let (state, _dir, admin_id) = seeded_state().await;
        let cookie = admin_cookie(&state, admin_id).await;
        let org_id = state.persistence.list_orgs().await.unwrap()[0].id;
        let app = crate::http::server::router(state);

        // POST create a user with a plaintext password.
        let payload = format!(
            r#"{{"name":"bob","org_id":{org_id},"password":"pw","enabled":true,"is_admin":true}}"#
        );
        let resp = app
            .clone()
            .oneshot(
                Request::post("/admin/users")
                    .header(header::COOKIE, &cookie)
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(payload))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let created: serde_json::Value = serde_json::from_slice(&body).unwrap();
        let id = created["id"].as_i64().unwrap();
        assert!(created.get("password").is_none(), "no hash on create resp");

        // GET → redacted view: no hash, has_password:true.
        let resp = app
            .clone()
            .oneshot(
                Request::get(format!("/admin/users/{id}"))
                    .header(header::COOKIE, &cookie)
                    .body(Body::empty())
                    .unwrap(),
            )
            .await
            .unwrap();
        let body = resp.into_body().collect().await.unwrap().to_bytes();
        let view: serde_json::Value = serde_json::from_slice(&body).unwrap();
        assert!(view.get("password").is_none(), "GET must not leak the hash");
        assert_eq!(view["has_password"], true);

        // Login as bob with "pw" proves the stored hash is valid.
        let resp = app
            .oneshot(
                Request::post("/admin/login")
                    .header(header::CONTENT_TYPE, "application/json")
                    .body(Body::from(r#"{"username":"bob","password":"pw"}"#))
                    .unwrap(),
            )
            .await
            .unwrap();
        assert_eq!(resp.status(), StatusCode::OK);
    }
}
