import type { TemplateRoute } from "../../types";

export const DISPATCH_TEMPLATE_ROUTES: readonly TemplateRoute[] = [
  ["ModelList", "OpenAi", "ModelList", "OpenAi"],
  ["ModelList", "Claude", "ModelList", "OpenAi"],
  ["ModelList", "Gemini", "ModelList", "OpenAi"],
  ["ModelGet", "OpenAi", "ModelGet", "OpenAi"],
  ["ModelGet", "Claude", "ModelGet", "OpenAi"],
  ["ModelGet", "Gemini", "ModelGet", "OpenAi"],
  ["CountToken", "OpenAi", "CountToken", "OpenAi"],
  ["CountToken", "Claude", "CountToken", "OpenAi"],
  ["CountToken", "Gemini", "CountToken", "OpenAi"],
  ["GenerateContent", "OpenAi", "GenerateContent", "OpenAi"],
  ["GenerateContent", "OpenAiChatCompletion", "GenerateContent", "OpenAiChatCompletion"],
  ["GenerateContent", "Claude", "GenerateContent", "OpenAi"],
  ["GenerateContent", "Gemini", "GenerateContent", "OpenAi"],
  ["OpenAiResponseWebSocket", "OpenAi", "StreamGenerateContent", "OpenAi"],
  ["GeminiLive", "Gemini", "StreamGenerateContent", "OpenAi"],
  ["StreamGenerateContent", "OpenAi", "StreamGenerateContent", "OpenAi"],
  ["StreamGenerateContent", "OpenAiChatCompletion", "StreamGenerateContent", "OpenAiChatCompletion"],
  ["StreamGenerateContent", "Claude", "StreamGenerateContent", "OpenAi"],
  ["StreamGenerateContent", "Gemini", "StreamGenerateContent", "OpenAi"],
  ["StreamGenerateContent", "GeminiNDJson", "StreamGenerateContent", "OpenAi"],
  ["Embedding", "OpenAi", "Embedding", "OpenAi"],
  ["Embedding", "Gemini", "Embedding", "OpenAi"],
  ["Compact", "OpenAi", "Compact", "OpenAi"],
];
