/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PortalRouteImport } from './routes/_portal'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppUsersIndexRouteImport } from './routes/_app/users/index'
import { Route as AppUsageIndexRouteImport } from './routes/_app/usage/index'
import { Route as AppUpdateIndexRouteImport } from './routes/_app/update/index'
import { Route as AppSettingsIndexRouteImport } from './routes/_app/settings/index'
import { Route as AppRulesIndexRouteImport } from './routes/_app/rules/index'
import { Route as AppRoutesIndexRouteImport } from './routes/_app/routes/index'
import { Route as AppProvidersIndexRouteImport } from './routes/_app/providers/index'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as AppUsersUserIdRouteImport } from './routes/_app/users/$userId'
import { Route as AppRulesRuleSetIdRouteImport } from './routes/_app/rules/$ruleSetId'
import { Route as AppRoutesRouteIdRouteImport } from './routes/_app/routes/$routeId'
import { Route as AppProvidersProviderIdRouteImport } from './routes/_app/providers/$providerId'
import { Route as AppOrgsOrgIdRouteImport } from './routes/_app/orgs/$orgId'
import { Route as PortalAccountUsageIndexRouteImport } from './routes/_portal/account/usage/index'
import { Route as PortalAccountLimitsIndexRouteImport } from './routes/_portal/account/limits/index'
import { Route as PortalAccountKeysIndexRouteImport } from './routes/_portal/account/keys/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/_portal',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersIndexRoute = AppUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsageIndexRoute = AppUsageIndexRouteImport.update({
  id: '/usage/',
  path: '/usage/',
  getParentRoute: () => AppRoute,
} as any)
const AppUpdateIndexRoute = AppUpdateIndexRouteImport.update({
  id: '/update/',
  path: '/update/',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsIndexRoute = AppSettingsIndexRouteImport.update({
  id: '/settings/',
  path: '/settings/',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesIndexRoute = AppRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesIndexRoute = AppRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRoute,
} as any)
const AppUsersUserIdRoute = AppUsersUserIdRouteImport.update({
  id: '/users/$userId',
  path: '/users/$userId',
  getParentRoute: () => AppRoute,
} as any)
const AppRulesRuleSetIdRoute = AppRulesRuleSetIdRouteImport.update({
  id: '/rules/$ruleSetId',
  path: '/rules/$ruleSetId',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRouteIdRoute = AppRoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersProviderIdRoute = AppProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsOrgIdRoute = AppOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AppRoute,
} as any)
const PortalAccountUsageIndexRoute = PortalAccountUsageIndexRouteImport.update({
  id: '/account/usage/',
  path: '/account/usage/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAccountLimitsIndexRoute =
  PortalAccountLimitsIndexRouteImport.update({
    id: '/account/limits/',
    path: '/account/limits/',
    getParentRoute: () => PortalRoute,
  } as any)
const PortalAccountKeysIndexRoute = PortalAccountKeysIndexRouteImport.update({
  id: '/account/keys/',
  path: '/account/keys/',
  getParentRoute: () => PortalRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/rules/$ruleSetId': typeof AppRulesRuleSetIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/orgs/': typeof AppOrgsIndexRoute
  '/providers/': typeof AppProvidersIndexRoute
  '/routes/': typeof AppRoutesIndexRoute
  '/rules/': typeof AppRulesIndexRoute
  '/settings/': typeof AppSettingsIndexRoute
  '/update/': typeof AppUpdateIndexRoute
  '/usage/': typeof AppUsageIndexRoute
  '/users/': typeof AppUsersIndexRoute
  '/account/keys/': typeof PortalAccountKeysIndexRoute
  '/account/limits/': typeof PortalAccountLimitsIndexRoute
  '/account/usage/': typeof PortalAccountUsageIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/rules/$ruleSetId': typeof AppRulesRuleSetIdRoute
  '/users/$userId': typeof AppUsersUserIdRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/providers': typeof AppProvidersIndexRoute
  '/routes': typeof AppRoutesIndexRoute
  '/rules': typeof AppRulesIndexRoute
  '/settings': typeof AppSettingsIndexRoute
  '/update': typeof AppUpdateIndexRoute
  '/usage': typeof AppUsageIndexRoute
  '/users': typeof AppUsersIndexRoute
  '/account/keys': typeof PortalAccountKeysIndexRoute
  '/account/limits': typeof PortalAccountLimitsIndexRoute
  '/account/usage': typeof PortalAccountUsageIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_portal': typeof PortalRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/_app/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/_app/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/_app/rules/$ruleSetId': typeof AppRulesRuleSetIdRoute
  '/_app/users/$userId': typeof AppUsersUserIdRoute
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
  '/_app/routes/': typeof AppRoutesIndexRoute
  '/_app/rules/': typeof AppRulesIndexRoute
  '/_app/settings/': typeof AppSettingsIndexRoute
  '/_app/update/': typeof AppUpdateIndexRoute
  '/_app/usage/': typeof AppUsageIndexRoute
  '/_app/users/': typeof AppUsersIndexRoute
  '/_portal/account/keys/': typeof PortalAccountKeysIndexRoute
  '/_portal/account/limits/': typeof PortalAccountLimitsIndexRoute
  '/_portal/account/usage/': typeof PortalAccountUsageIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orgs/$orgId'
    | '/providers/$providerId'
    | '/routes/$routeId'
    | '/rules/$ruleSetId'
    | '/users/$userId'
    | '/orgs/'
    | '/providers/'
    | '/routes/'
    | '/rules/'
    | '/settings/'
    | '/update/'
    | '/usage/'
    | '/users/'
    | '/account/keys/'
    | '/account/limits/'
    | '/account/usage/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/orgs/$orgId'
    | '/providers/$providerId'
    | '/routes/$routeId'
    | '/rules/$ruleSetId'
    | '/users/$userId'
    | '/orgs'
    | '/providers'
    | '/routes'
    | '/rules'
    | '/settings'
    | '/update'
    | '/usage'
    | '/users'
    | '/account/keys'
    | '/account/limits'
    | '/account/usage'
  id:
    | '__root__'
    | '/_app'
    | '/_portal'
    | '/login'
    | '/_app/'
    | '/_app/orgs/$orgId'
    | '/_app/providers/$providerId'
    | '/_app/routes/$routeId'
    | '/_app/rules/$ruleSetId'
    | '/_app/users/$userId'
    | '/_app/orgs/'
    | '/_app/providers/'
    | '/_app/routes/'
    | '/_app/rules/'
    | '/_app/settings/'
    | '/_app/update/'
    | '/_app/usage/'
    | '/_app/users/'
    | '/_portal/account/keys/'
    | '/_portal/account/limits/'
    | '/_portal/account/usage/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  PortalRoute: typeof PortalRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_portal': {
      id: '/_portal'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/': {
      id: '/_app/users/'
      path: '/users'
      fullPath: '/users/'
      preLoaderRoute: typeof AppUsersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/usage/': {
      id: '/_app/usage/'
      path: '/usage'
      fullPath: '/usage/'
      preLoaderRoute: typeof AppUsageIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/update/': {
      id: '/_app/update/'
      path: '/update'
      fullPath: '/update/'
      preLoaderRoute: typeof AppUpdateIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings/': {
      id: '/_app/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AppSettingsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules/': {
      id: '/_app/rules/'
      path: '/rules'
      fullPath: '/rules/'
      preLoaderRoute: typeof AppRulesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/': {
      id: '/_app/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof AppRoutesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/users/$userId': {
      id: '/_app/users/$userId'
      path: '/users/$userId'
      fullPath: '/users/$userId'
      preLoaderRoute: typeof AppUsersUserIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rules/$ruleSetId': {
      id: '/_app/rules/$ruleSetId'
      path: '/rules/$ruleSetId'
      fullPath: '/rules/$ruleSetId'
      preLoaderRoute: typeof AppRulesRuleSetIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/$routeId': {
      id: '/_app/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof AppRoutesRouteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/$providerId': {
      id: '/_app/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof AppProvidersProviderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId': {
      id: '/_app/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AppOrgsOrgIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_portal/account/usage/': {
      id: '/_portal/account/usage/'
      path: '/account/usage'
      fullPath: '/account/usage/'
      preLoaderRoute: typeof PortalAccountUsageIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/limits/': {
      id: '/_portal/account/limits/'
      path: '/account/limits'
      fullPath: '/account/limits/'
      preLoaderRoute: typeof PortalAccountLimitsIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_portal/account/keys/': {
      id: '/_portal/account/keys/'
      path: '/account/keys'
      fullPath: '/account/keys/'
      preLoaderRoute: typeof PortalAccountKeysIndexRouteImport
      parentRoute: typeof PortalRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOrgsOrgIdRoute: typeof AppOrgsOrgIdRoute
  AppProvidersProviderIdRoute: typeof AppProvidersProviderIdRoute
  AppRoutesRouteIdRoute: typeof AppRoutesRouteIdRoute
  AppRulesRuleSetIdRoute: typeof AppRulesRuleSetIdRoute
  AppUsersUserIdRoute: typeof AppUsersUserIdRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
  AppRoutesIndexRoute: typeof AppRoutesIndexRoute
  AppRulesIndexRoute: typeof AppRulesIndexRoute
  AppSettingsIndexRoute: typeof AppSettingsIndexRoute
  AppUpdateIndexRoute: typeof AppUpdateIndexRoute
  AppUsageIndexRoute: typeof AppUsageIndexRoute
  AppUsersIndexRoute: typeof AppUsersIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOrgsOrgIdRoute: AppOrgsOrgIdRoute,
  AppProvidersProviderIdRoute: AppProvidersProviderIdRoute,
  AppRoutesRouteIdRoute: AppRoutesRouteIdRoute,
  AppRulesRuleSetIdRoute: AppRulesRuleSetIdRoute,
  AppUsersUserIdRoute: AppUsersUserIdRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
  AppRoutesIndexRoute: AppRoutesIndexRoute,
  AppRulesIndexRoute: AppRulesIndexRoute,
  AppSettingsIndexRoute: AppSettingsIndexRoute,
  AppUpdateIndexRoute: AppUpdateIndexRoute,
  AppUsageIndexRoute: AppUsageIndexRoute,
  AppUsersIndexRoute: AppUsersIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

interface PortalRouteChildren {
  PortalAccountKeysIndexRoute: typeof PortalAccountKeysIndexRoute
  PortalAccountLimitsIndexRoute: typeof PortalAccountLimitsIndexRoute
  PortalAccountUsageIndexRoute: typeof PortalAccountUsageIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAccountKeysIndexRoute: PortalAccountKeysIndexRoute,
  PortalAccountLimitsIndexRoute: PortalAccountLimitsIndexRoute,
  PortalAccountUsageIndexRoute: PortalAccountUsageIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  PortalRoute: PortalRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
