/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app/index'
import { Route as AppRoutesIndexRouteImport } from './routes/_app/routes/index'
import { Route as AppProvidersIndexRouteImport } from './routes/_app/providers/index'
import { Route as AppOrgsIndexRouteImport } from './routes/_app/orgs/index'
import { Route as AppRoutesRouteIdRouteImport } from './routes/_app/routes/$routeId'
import { Route as AppProvidersProviderIdRouteImport } from './routes/_app/providers/$providerId'
import { Route as AppOrgsOrgIdRouteImport } from './routes/_app/orgs/$orgId'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesIndexRoute = AppRoutesIndexRouteImport.update({
  id: '/routes/',
  path: '/routes/',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersIndexRoute = AppProvidersIndexRouteImport.update({
  id: '/providers/',
  path: '/providers/',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsIndexRoute = AppOrgsIndexRouteImport.update({
  id: '/orgs/',
  path: '/orgs/',
  getParentRoute: () => AppRoute,
} as any)
const AppRoutesRouteIdRoute = AppRoutesRouteIdRouteImport.update({
  id: '/routes/$routeId',
  path: '/routes/$routeId',
  getParentRoute: () => AppRoute,
} as any)
const AppProvidersProviderIdRoute = AppProvidersProviderIdRouteImport.update({
  id: '/providers/$providerId',
  path: '/providers/$providerId',
  getParentRoute: () => AppRoute,
} as any)
const AppOrgsOrgIdRoute = AppOrgsOrgIdRouteImport.update({
  id: '/orgs/$orgId',
  path: '/orgs/$orgId',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/login': typeof LoginRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/orgs/': typeof AppOrgsIndexRoute
  '/providers/': typeof AppProvidersIndexRoute
  '/routes/': typeof AppRoutesIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/': typeof AppIndexRoute
  '/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/orgs': typeof AppOrgsIndexRoute
  '/providers': typeof AppProvidersIndexRoute
  '/routes': typeof AppRoutesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/_app/': typeof AppIndexRoute
  '/_app/orgs/$orgId': typeof AppOrgsOrgIdRoute
  '/_app/providers/$providerId': typeof AppProvidersProviderIdRoute
  '/_app/routes/$routeId': typeof AppRoutesRouteIdRoute
  '/_app/orgs/': typeof AppOrgsIndexRoute
  '/_app/providers/': typeof AppProvidersIndexRoute
  '/_app/routes/': typeof AppRoutesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/orgs/$orgId'
    | '/providers/$providerId'
    | '/routes/$routeId'
    | '/orgs/'
    | '/providers/'
    | '/routes/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/'
    | '/orgs/$orgId'
    | '/providers/$providerId'
    | '/routes/$routeId'
    | '/orgs'
    | '/providers'
    | '/routes'
  id:
    | '__root__'
    | '/_app'
    | '/login'
    | '/_app/'
    | '/_app/orgs/$orgId'
    | '/_app/providers/$providerId'
    | '/_app/routes/$routeId'
    | '/_app/orgs/'
    | '/_app/providers/'
    | '/_app/routes/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/': {
      id: '/_app/routes/'
      path: '/routes'
      fullPath: '/routes/'
      preLoaderRoute: typeof AppRoutesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/': {
      id: '/_app/providers/'
      path: '/providers'
      fullPath: '/providers/'
      preLoaderRoute: typeof AppProvidersIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/': {
      id: '/_app/orgs/'
      path: '/orgs'
      fullPath: '/orgs/'
      preLoaderRoute: typeof AppOrgsIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/routes/$routeId': {
      id: '/_app/routes/$routeId'
      path: '/routes/$routeId'
      fullPath: '/routes/$routeId'
      preLoaderRoute: typeof AppRoutesRouteIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/providers/$providerId': {
      id: '/_app/providers/$providerId'
      path: '/providers/$providerId'
      fullPath: '/providers/$providerId'
      preLoaderRoute: typeof AppProvidersProviderIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/orgs/$orgId': {
      id: '/_app/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AppOrgsOrgIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppIndexRoute: typeof AppIndexRoute
  AppOrgsOrgIdRoute: typeof AppOrgsOrgIdRoute
  AppProvidersProviderIdRoute: typeof AppProvidersProviderIdRoute
  AppRoutesRouteIdRoute: typeof AppRoutesRouteIdRoute
  AppOrgsIndexRoute: typeof AppOrgsIndexRoute
  AppProvidersIndexRoute: typeof AppProvidersIndexRoute
  AppRoutesIndexRoute: typeof AppRoutesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppIndexRoute: AppIndexRoute,
  AppOrgsOrgIdRoute: AppOrgsOrgIdRoute,
  AppProvidersProviderIdRoute: AppProvidersProviderIdRoute,
  AppRoutesRouteIdRoute: AppRoutesRouteIdRoute,
  AppOrgsIndexRoute: AppOrgsIndexRoute,
  AppProvidersIndexRoute: AppProvidersIndexRoute,
  AppRoutesIndexRoute: AppRoutesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
